#!/bin/sh
# Regenerates internal/catalog/filterable_gen.go from the SDK's OpenAPI spec:
# the attributes each list endpoint documents as filterable in its `where`
# parameter description. Run after bumping github.com/confighub/sdk/core.
set -e
SPEC="$(go env GOMODCACHE)/github.com/confighub/sdk/core@$(go list -m -f '{{.Version}}' github.com/confighub/sdk/core)/openapi/openapi.json"
OUT=internal/catalog/filterable_gen.go
{
  echo '// Code generated by hack/gen-filterable.sh; DO NOT EDIT.'
  echo
  echo 'package catalog'
  echo
  echo '// filterable lists, per entity, the attributes the server accepts in a where clause.'
  echo 'var filterable = map[string][]string{'
  jq -r '.paths | to_entries[] | select(.value.get != null) | .value.get.parameters[]? | select(.name=="where") | .description | capture("Supported attributes for filtering on (?<e>[A-Za-z]+): (?<a>[^.]+)\\.") | "\t\"\(.e)\": {\(.a | split(", ") | map("\"" + . + "\"") | join(", "))},"' "$SPEC" | sort -u
  echo '}'
} > "$OUT"
gofmt -w "$OUT"
echo "wrote $OUT"
