// Code generated by hack/gen-filterable.sh; DO NOT EDIT.

package catalog

// filterable lists, per entity, the attributes the server accepts in a where clause.
var filterable = map[string][]string{
	"Attribute":          {"Annotations", "AttributeID", "CreatedAt", "DataType", "DeleteGates", "DisplayName", "Hash", "Labels", "OrganizationID", "Slug", "SpaceID", "ToolchainType", "UpdatedAt"},
	"BridgeWorker":       {"Annotations", "BridgeWorkerID", "Condition", "CreatedAt", "DisplayName", "IPAddress", "Labels", "LastMessage", "LastSeenAt", "OrgRole", "OrganizationID", "Permissions", "Slug", "SpaceID", "UpdatedAt", "UserID"},
	"ChangeOrder":        {"AbortedReason", "AdoptedEndTagID", "Annotations", "ChangeOrderID", "CreatedAt", "DeleteGates", "Description", "DisplayName", "EndTagID", "InScopeSpaceIDs", "Labels", "OrganizationID", "ReleasedSpaceIDs", "ResolvedSpaceIDs", "SkippedUnits", "Slug", "SpaceID", "StartTagID", "State", "UpdateType", "UpdatedAt"},
	"ChangeSet":          {"Annotations", "ChangeSetID", "CreatedAt", "DeleteGates", "Description", "DisplayName", "EndTagID", "Labels", "OrganizationID", "Slug", "SpaceID", "StartTagID", "StartTagIsPriorRevision", "State", "UpdatedAt"},
	"Filter":             {"Annotations", "CreatedAt", "DeleteGates", "DisplayName", "FilterID", "From", "FromSpaceID", "Hash", "Labels", "OrganizationID", "ResourceType", "Slug", "SpaceID", "UpdatedAt", "Where", "WhereData"},
	"FunctionSignature":  {"AttributeName", "Description", "FunctionName", "FunctionType", "Hermetic", "Idempotent", "Mutating", "OutputInfo"},
	"Invocation":         {"Annotations", "BridgeWorkerID", "CreatedAt", "DeleteGates", "DisplayName", "FunctionInvocations", "Hash", "InvocationID", "Labels", "OrganizationID", "Slug", "SpaceID", "ToolchainType", "UpdatedAt"},
	"Link":               {"Annotations", "AutoUpdate", "CreatedAt", "DeleteGates", "DisplayName", "DownstreamLastMergedRevisionNum", "FromUnitID", "Hash", "Labels", "LinkID", "MergeEnableSubtraction", "OrganizationID", "Protect", "Slug", "SpaceID", "Squash", "Stale", "ToSpaceID", "ToUnitID", "TransformInvocationID", "UpdateType", "UpdatedAt", "UpstreamLastMergedRevisionNum", "UpstreamLinkID", "UpstreamSpaceID"},
	"Mutation":           {"BridgeWorkerID", "CreatedAt", "FunctionName", "InvocationID", "InvocationParams", "LinkID", "MergeBaseRevisionNum", "MergeEndRevisionNum", "MergeSourceID", "MutationID", "MutationNum", "OrganizationID", "ReplayOutcome", "ReplayReason", "RestoredRevisionNum", "RevisionID", "RevisionNum", "SpaceID", "Subgroup", "TriggerID", "UnitID", "UpdatedAt", "UpgradedFromUpstreamRevisionNum"},
	"Organization":       {"Annotations", "CreatedAt", "DeleteGates", "DisplayName", "EmailDomain", "ExternalID", "Labels", "OrganizationID", "Slug", "UpdatedAt"},
	"OrganizationMember": {"DisplayName", "ExternalID", "Slug", "UserID", "Username"},
	"QueuedOperation":    {"Action", "BridgeWorkerID", "CreatedAt", "DryRun", "OrganizationID", "QueuedOperationID", "RevisionNum", "SpaceID", "Status", "TargetID", "UnitActionNum", "UnitID"},
	"Release":            {"Annotations", "CreatedAt", "DeleteGates", "Digest", "Labels", "ManifestDigest", "OrganizationID", "Published", "ReleaseID", "SpaceID", "TagID", "UnitCount", "UpdatedAt"},
	"Resource":           {"CreatedAt", "Data", "OrganizationID", "ResourceID", "ResourceIndex", "ResourceName", "ResourceType", "SpaceID", "TargetID", "ToolchainType", "UnitID", "UpdatedAt"},
	"Revision":           {"ApplyGates", "ApplyWarnings", "ApprovedBy", "ChangeOrders", "ChangeSetID", "Conflicts", "CreatedAt", "DataHash", "Description", "OrganizationID", "Releases", "RevisionID", "RevisionNum", "Source", "SpaceID", "Tags", "UnitID", "UpdatedAt", "UserAgent", "UserID"},
	"Space":              {"Annotations", "AttributeFilterID", "AttributeHash", "AttributeIDs", "CreatedAt", "DeleteGates", "DisplayName", "Labels", "OrganizationID", "Permissions", "ReleaseBridgeWorkerID", "ReleaseTargetID", "Slug", "SpaceID", "TriggerFilterID", "TriggerHash", "TriggerIDs", "UpdatedAt"},
	"Tag":                {"Annotations", "ChangeOrderID", "ChangeSetID", "CreatedAt", "DeleteGates", "DisplayName", "Labels", "OrganizationID", "Slug", "SpaceID", "TagID", "UpdatedAt"},
	"Target":             {"Annotations", "BridgeHandle", "BridgeWorkerID", "CreatedAt", "DeleteGates", "DisplayName", "Facts", "Labels", "LiveStateType", "Options", "OrganizationID", "Permissions", "ProviderType", "Slug", "SpaceID", "TargetID", "ToolchainType", "TriggerFilterID", "TriggerHash", "TriggerIDs", "UpdatedAt"},
	"Trigger":            {"Annotations", "BridgeWorkerID", "CreatedAt", "DeleteGates", "Description", "Disabled", "DisplayName", "Event", "FunctionName", "Hash", "InvocationID", "Labels", "OrganizationID", "OtherDataSource", "Protect", "Slug", "SpaceID", "ToolchainType", "TriggerID", "UnitFilterID", "UpdatedAt", "Validating", "Warn", "WhereResource", "WhereUnit"},
	"Unit":               {"Annotations", "ApplyGates", "ApplyWarnings", "ApprovedBy", "BridgeWorkerID", "ChangeSetID", "Conflicts", "CreatedAt", "DataHash", "DeleteGates", "DestroyGates", "DisplayName", "FromLinkID", "HeadRevisionNum", "HeadUnitActionNum", "HeadUnitEventNum", "Labels", "LastActionAt", "LastChangeDescription", "LastReleasedRevisionNum", "OrganizationID", "ProviderType", "Slug", "SpaceID", "TargetID", "TargetOptions", "ToolchainType", "UnitID", "UpdatedAt", "UpstreamRevisionNum", "UpstreamSpaceID", "UpstreamUnitID", "Values"},
	"UnitEvent":          {"Action", "BridgeWorkerID", "CreatedAt", "OrganizationID", "QueuedOperationID", "Result", "RevisionNum", "SpaceID", "StartedAt", "Status", "TerminatedAt", "UnitEventID", "UnitEventNum", "UnitID", "UpdatedAt"},
	"User":               {"CreatedAt", "DisplayName", "ExternalID", "Slug", "UpdatedAt", "UserID", "Username"},
	"View":               {"Annotations", "CreatedAt", "DisplayName", "FilterID", "GroupBy", "Labels", "Of", "OrderBy", "OrderByDirection", "OrganizationID", "Slug", "SpaceID", "UpdatedAt", "ViewID"},
}
